# Workaround for https://github.com/travis-ci/travis-ci/issues/8363
language: cpp
#  - minimal

os:
  - linux

# Container-based infrastructure (Linux)
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
sudo:
  - false

# Install packages differs for container-based infrastructure
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-do-I-install-APT-sources-and-packages%3F
addons:
  apt:
    packages:
      - python3
      - cmake
#      - enchant # for documentation

#dist:
#  - trusty

env:
  global: 
    - HUNTER_STATUS_DEBUG=ON
    - CMAKE_VERBOSE_MAKEFILE=ON
    - CONFIG=Release

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
          - TOOLCHAIN=gcc-5-cxx14-c11

    # works on Precise and Trusty
    #- os: linux
    #  addons:
    #    apt:
    #      sources:
    #        - ubuntu-toolchain-r-test
    #      packages:
    #        - g++-6
    #  env:
          #- MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    # works on Precise and Trusty
    #- os: linux
    #  addons:
    #    apt:
    #      sources:
    #        - ubuntu-toolchain-r-test
    #      packages:
    #        - g++-7
    #  env:
          #- MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          #packages:
          #  - g++-7
      env:
          - TOOLCHAIN=clang-5-cxx14



install:
  # Info about OS
  - uname -a

  - if [[ "`uname`" == "Linux" ]]; then  mkdir clang-bin; ln -s /usr/local/clang-5.0.0/bin/clang++ clang-bin/clang++-5.0; fi
- if [[ "`uname`" == "Darwin" ]]; then mkdir clang-bin; ln -s /usr/bin/clang++ clang-bin/clang++-5.0; fi

  # Install latest Polly toolchains and scripts
  - wget https://github.com/ruslo/polly/archive/master.zip
  - unzip master.zip
  - POLLY_ROOT="`pwd`/polly-master"
  - export PATH="${POLLY_ROOT}/bin:${PATH}"

script:
#  - > 
#    cmake -H. 
#          -B_builds/${TOOLCHAIN}
#          -DCMAKE_TOOLCHAIN_FILE=${POLLY_ROOT}/${TOOLCHAIN}.cmake 
#          -DCMAKE_VERBOSE_MAKEFILE=ON
  - >
    python3 "${POLLY_ROOT}/bin/build.py"
    --home .
    --toolchain ${TOOLCHAIN}
    --config ${CONFIG}
    --verbose
    --clear
    #--install
    --test

before_install:
    - eval "${MATRIX_EVAL}"
